package com.dps.home;

import java.awt.Color;
/**
 *
 * @author Rutvik
 */
public class Home extends javax.swing.JFrame {
    
    public Home() {
        initComponents();
        this.setTitle("Welcome!");
        this.getContentPane().setBackground(Color.black);   
    }
    
    private void go()
    {
        Login l=new Login();
        l.setVisible(true);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redBanner = new javax.swing.JLabel();
        neonBanner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        redBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dps/img/generatedtext.jpg"))); // NOI18N
        redBanner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redBannerMouseClicked(evt);
            }
        });
        getContentPane().add(redBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, -1));

        neonBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dps/img/imagesMGMICBTC.jpg"))); // NOI18N
        neonBanner.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        neonBanner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                neonBannerMouseClicked(evt);
            }
        });
        getContentPane().add(neonBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 530, 380));

        setSize(new java.awt.Dimension(1182, 632));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        go(); 
    }//GEN-LAST:event_formMouseClicked

    private void neonBannerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_neonBannerMouseClicked
        go();    
    }//GEN-LAST:event_neonBannerMouseClicked

    private void redBannerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redBannerMouseClicked
        go();        
    }//GEN-LAST:event_redBannerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel neonBanner;
    private javax.swing.JLabel redBanner;
    // End of variables declaration//GEN-END:variables
}
